Animation:
  camera: mastercam
  camera_options:
    depthOfField: false
    displayFieldChart: false
    displayFilmGate: false
    displayFilmOrigin: false
    displayFilmPivot: false
    displayGateMask: false
    displayResolution: false
    displaySafeAction: false
    displaySafeTitle: false
    overscan: 1.0
  display_options:
    background:
    - 0.6309999823570251
    - 0.6309999823570251
    - 0.6309999823570251
    backgroundBottom:
    - 0.052000001072883606
    - 0.052000001072883606
    - 0.052000001072883606
    backgroundTop:
    - 0.5350000262260437
    - 0.6169999837875366
    - 0.7020000219345093
    displayGradient: true
  viewport2_options:
    bumpBakeResolution: 64
    colorBakeResolution: 64
    consolidateWorld: true
    enableTextureMaxRes: false
    floatingPointRTEnable: true
    floatingPointRTFormat: 1
    gammaCorrectionEnable: false
    gammaValue: 2.200000047683716
    holdOutDetailMode: 1
    holdOutMode: true
    hwFogAlpha: 1.0
    hwFogColorB: 0.5
    hwFogColorG: 0.5
    hwFogColorR: 0.5
    hwFogDensity: 0.10000000149011612
    hwFogEnable: false
    hwFogEnd: 100.0
    hwFogFalloff: 0
    hwFogStart: 0.0
    lineAAEnable: false
    maxHardwareLights: 8
    motionBlurEnable: false
    motionBlurSampleCount: 8
    motionBlurShutterOpenFraction: 0.20000000298023224
    motionBlurType: 0
    multiSampleCount: 8
    multiSampleEnable: false
    singleSidedLighting: false
    ssaoAmount: 1.0
    ssaoEnable: false
    ssaoFilterRadius: 16
    ssaoRadius: 16
    ssaoSamples: 16
    textureMaxResolution: 4096
    transparencyAlgorithm: 1
    transparencyQuality: 0.33000001311302185
    useMaximumHardwareLights: true
    vertexAnimationCache: 0
  viewport_options:
    cameras: false
    controlVertices: false
    deformers: false
    dimensions: false
    displayAppearance: smoothShaded
    displayLights: default
    displayTextures: false
    dynamicConstraints: false
    dynamics: false
    fluids: false
    fogColor:
    - 0.5
    - 0.5
    - 0.5
    - 1.0
    fogDensity: 0.10000000149011612
    fogEnd: 100.0
    fogMode: linear
    fogStart: 0.0
    fogging: false
    follicles: false
    grid: false
    hairSystems: false
    handles: false
    headsUpDisplay: true
    hulls: false
    ikHandles: false
    imagePlane: false
    joints: false
    lights: false
    locators: false
    manipulators: true
    nCloths: false
    nParticles: false
    nRigids: false
    nurbsCurves: true
    nurbsSurfaces: false
    pivots: false
    planes: false
    polymeshes: true
    rendererName: vp2Renderer
    selectionHiliteDisplay: true
    shadows: true
    strokes: false
    subdivSurfaces: false
    textures: false
    useDefaultMaterial: false
    wireframeOnShaded: false
Final:
  camera: mastercam
  camera_options:
    depthOfField: false
    displayFieldChart: false
    displayFilmGate: false
    displayFilmOrigin: false
    displayFilmPivot: false
    displayGateMask: true
    displayResolution: false
    displaySafeAction: false
    displaySafeTitle: false
    overscan: 1.0
  display_options:
    background:
    - 0.4569999873638153
    - 0.4569999873638153
    - 0.4569999873638153
    backgroundBottom:
    - 0.2840000092983246
    - 0.2840000092983246
    - 0.2840000092983246
    backgroundTop:
    - 0.9380000233650208
    - 0.9683870077133179
    - 1.0
    displayGradient: true
  viewport2_options:
    bumpBakeResolution: 64
    colorBakeResolution: 64
    consolidateWorld: true
    enableTextureMaxRes: false
    floatingPointRTEnable: true
    floatingPointRTFormat: 1
    gammaCorrectionEnable: false
    gammaValue: 2.200000047683716
    holdOutDetailMode: 1
    holdOutMode: true
    hwFogAlpha: 1.0
    hwFogColorB: 0.5
    hwFogColorG: 0.5
    hwFogColorR: 0.5
    hwFogDensity: 0.10000000149011612
    hwFogEnable: false
    hwFogEnd: 30.150753021240234
    hwFogFalloff: 0
    hwFogStart: 15.075377464294434
    lineAAEnable: false
    maxHardwareLights: 8
    motionBlurEnable: false
    motionBlurSampleCount: 16
    motionBlurShutterOpenFraction: 0.3050000071525574
    motionBlurType: 0
    multiSampleCount: 8
    multiSampleEnable: true
    singleSidedLighting: false
    ssaoAmount: 1.0
    ssaoEnable: true
    ssaoFilterRadius: 16
    ssaoRadius: 16
    ssaoSamples: 16
    textureMaxResolution: 4096
    transparencyAlgorithm: 1
    transparencyQuality: 0.33000001311302185
    useMaximumHardwareLights: true
    vertexAnimationCache: 0
  viewport_options:
    cameras: false
    controlVertices: false
    deformers: false
    dimensions: false
    displayAppearance: smoothShaded
    displayLights: all
    displayTextures: true
    dynamicConstraints: false
    dynamics: false
    fluids: false
    fogColor:
    - 0.5
    - 0.5
    - 0.5
    - 1.0
    fogDensity: 0.10000000149011612
    fogEnd: 100.0
    fogMode: linear
    fogStart: 0.0
    fogging: false
    follicles: false
    grid: false
    hairSystems: false
    handles: false
    headsUpDisplay: true
    hulls: false
    ikHandles: false
    imagePlane: false
    joints: false
    lights: false
    locators: false
    manipulators: true
    nCloths: false
    nParticles: false
    nRigids: false
    nurbsCurves: false
    nurbsSurfaces: false
    pivots: false
    planes: false
    polymeshes: true
    rendererName: vp2Renderer
    selectionHiliteDisplay: true
    shadows: true
    strokes: false
    subdivSurfaces: true
    textures: false
    useDefaultMaterial: false
    wireframeOnShaded: false
Grey:
  camera: mastercam
  camera_options:
    depthOfField: false
    displayFieldChart: false
    displayFilmGate: false
    displayFilmOrigin: false
    displayFilmPivot: false
    displayGateMask: true
    displayResolution: true
    displaySafeAction: false
    displaySafeTitle: true
    overscan: 1.3
  display_options:
    background:
    - 0.6309999823570251
    - 0.6309999823570251
    - 0.6309999823570251
    backgroundBottom:
    - 0.052000001072883606
    - 0.052000001072883606
    - 0.052000001072883606
    backgroundTop:
    - 0.5350000262260437
    - 0.6169999837875366
    - 0.7020000219345093
    displayGradient: true
  viewport2_options:
    bumpBakeResolution: 64
    colorBakeResolution: 64
    consolidateWorld: true
    enableTextureMaxRes: false
    floatingPointRTEnable: true
    floatingPointRTFormat: 1
    gammaCorrectionEnable: false
    gammaValue: 2.200000047683716
    holdOutDetailMode: 1
    holdOutMode: true
    hwFogAlpha: 1.0
    hwFogColorB: 0.5
    hwFogColorG: 0.5
    hwFogColorR: 0.5
    hwFogDensity: 0.10000000149011612
    hwFogEnable: false
    hwFogEnd: 100.0
    hwFogFalloff: 0
    hwFogStart: 0.0
    lineAAEnable: false
    maxHardwareLights: 8
    motionBlurEnable: false
    motionBlurSampleCount: 8
    motionBlurShutterOpenFraction: 0.20000000298023224
    motionBlurType: 0
    multiSampleCount: 8
    multiSampleEnable: true
    singleSidedLighting: false
    ssaoAmount: 1.0
    ssaoEnable: true
    ssaoFilterRadius: 16
    ssaoRadius: 16
    ssaoSamples: 16
    textureMaxResolution: 4096
    transparencyAlgorithm: 1
    transparencyQuality: 0.33000001311302185
    useMaximumHardwareLights: true
    vertexAnimationCache: 0
  viewport_options:
    cameras: false
    controlVertices: false
    deformers: false
    dimensions: false
    displayAppearance: smoothShaded
    displayLights: all
    displayTextures: false
    dynamicConstraints: false
    dynamics: false
    fluids: false
    fogColor:
    - 0.5
    - 0.5
    - 0.5
    - 1.0
    fogDensity: 0.10000000149011612
    fogEnd: 100.0
    fogMode: linear
    fogStart: 0.0
    fogging: false
    follicles: false
    grid: false
    hairSystems: false
    handles: false
    headsUpDisplay: true
    hulls: false
    ikHandles: false
    imagePlane: false
    joints: false
    lights: false
    locators: false
    manipulators: true
    nCloths: false
    nParticles: false
    nRigids: false
    nurbsCurves: false
    nurbsSurfaces: false
    pivots: false
    planes: false
    polymeshes: true
    rendererName: vp2Renderer
    selectionHiliteDisplay: true
    shadows: true
    strokes: false
    subdivSurfaces: false
    textures: false
    useDefaultMaterial: false
    wireframeOnShaded: true
silhouette:
  camera: mastercam
  camera_options:
    depthOfField: false
    displayFieldChart: false
    displayFilmGate: false
    displayFilmOrigin: false
    displayFilmPivot: false
    displayGateMask: false
    displayResolution: true
    displaySafeAction: false
    displaySafeTitle: false
    overscan: 1.3
  display_options:
    background:
    - 0.0
    - 0.0
    - 0.0
    backgroundBottom:
    - 0.052000001072883606
    - 0.052000001072883606
    - 0.052000001072883606
    backgroundTop:
    - 0.5350000262260437
    - 0.6169999837875366
    - 0.7020000219345093
    displayGradient: false
  viewport2_options:
    bumpBakeResolution: 64
    colorBakeResolution: 64
    consolidateWorld: true
    enableTextureMaxRes: false
    floatingPointRTEnable: true
    floatingPointRTFormat: 1
    gammaCorrectionEnable: false
    gammaValue: 2.200000047683716
    holdOutDetailMode: 1
    holdOutMode: true
    hwFogAlpha: 1.0
    hwFogColorB: 0.5
    hwFogColorG: 0.5
    hwFogColorR: 0.5
    hwFogDensity: 0.10000000149011612
    hwFogEnable: false
    hwFogEnd: 100.0
    hwFogFalloff: 0
    hwFogStart: 0.0
    lineAAEnable: false
    maxHardwareLights: 8
    motionBlurEnable: false
    motionBlurSampleCount: 8
    motionBlurShutterOpenFraction: 0.20000000298023224
    motionBlurType: 0
    multiSampleCount: 8
    multiSampleEnable: true
    singleSidedLighting: false
    ssaoAmount: 1.0
    ssaoEnable: false
    ssaoFilterRadius: 16
    ssaoRadius: 16
    ssaoSamples: 16
    textureMaxResolution: 4096
    transparencyAlgorithm: 1
    transparencyQuality: 0.33000001311302185
    useMaximumHardwareLights: true
    vertexAnimationCache: 0
  viewport_options:
    cameras: false
    controlVertices: false
    deformers: false
    dimensions: false
    displayAppearance: smoothShaded
    displayLights: none
    displayTextures: false
    dynamicConstraints: false
    dynamics: false
    fluids: false
    fogColor:
    - 0.5
    - 0.5
    - 0.5
    - 1.0
    fogDensity: 0.10000000149011612
    fogEnd: 100.0
    fogMode: linear
    fogStart: 0.0
    fogging: false
    follicles: false
    grid: false
    hairSystems: false
    handles: false
    headsUpDisplay: true
    hulls: false
    ikHandles: false
    imagePlane: false
    joints: false
    lights: false
    locators: false
    manipulators: true
    nCloths: false
    nParticles: false
    nRigids: false
    nurbsCurves: false
    nurbsSurfaces: false
    pivots: false
    planes: false
    polymeshes: true
    rendererName: vp2Renderer
    selectionHiliteDisplay: true
    shadows: false
    strokes: false
    subdivSurfaces: false
    textures: false
    useDefaultMaterial: false
    wireframeOnShaded: false
